[package]
name = "Project"
version = "0.1.0"
authors = ["ION1ZED <iiionized@gmail.com>"]
edition = "2021"

[dependencies]
iced = { version = "0.7.0", features = ["image", "debug"] }
iced_native = "0.8.0"
iced_lazy = "0.4.0"
env_logger = "0.8"

serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}

ring = "0.16.20"
sha2 = "0.6.0"

async-std = { version = "1", features = ["attributes", "tokio1"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2.22", features = ["full"] }
serde_derive = "1.0"
dotenv = "0.15.0"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.15"
bitcoin = "0.13.2"
secp256k1 = { version = "0.25.0", features = ["rand-std", "bitcoin-hashes-std"] }